In [2]:
import awkward as ak
import uproot

In [3]:
file = uproot.open(
    "https://github.com/jpivarski-talks/2023-12-18-hsf-india-tutorial-bhubaneswar/raw/main/data/SMHiggsToZZTo4L.root"
)
tree = file["Events"]

muon_pt = tree["Muon_pt"].array(entry_stop=10)

In [4]:
particle_cut = muon_pt > 20
particle_cut

<Array [[True, True, False], [], [], ..., [], [], []] type='10 * var * bool'>

In [5]:
muon_pt

<Array [[63, 38.1, 4.05], [], [], ..., [], [], []] type='10 * var * float32'>

In [7]:
muon_pt[particle_cut]

<Array [[63, 38.1], [], [], [...], ..., [], [], []] type='10 * var * float32'>

In [8]:
idxs = ak.Array([
    [1],
    [],
    [],
    [0, 1],
    [],
    [1],
    [0],
    [],
    [],
    []
])

In [9]:
muon_pt[idxs]

<Array [[38.1], [], [], [54.3, ...], ..., [], [], []] type='10 * var * float32'>

In [29]:
aa = ak.Array([[0,1,2], [10,11,12], [20,21,22]])
ai = ak.Array([1, 2, 0])

In [15]:
aa[ai]

<Array [[10, 11, 12], [20, 21, 22]] type='2 * var * int64'>

In [16]:
ak.unzip(ai)

(<Array [1, 2] type='2 * int64'>,)

In [34]:
ai_nested = ak.unflatten(ai, 1)
ai_nested

<Array [[1], [2], [0]] type='3 * 1 * int64'>

In [46]:
aa[ai_nested]

<Array [[[10, 11, 12]], [[...]], [[0, 1, 2]]] type='3 * 1 * var * int64'>

In [37]:
aa[[[1],[2],[0]]]

<Array [[1], [12], [20]] type='3 * var * int64'>

In [43]:
aa[ai_nested.to_list()]

<Array [[1], [12], [20]] type='3 * var * int64'>

In [40]:
ai_nested.to_list() == [[1],[2],[0]]

True

In [47]:
import numpy as np

In [58]:
ni = np.array([1,2,0])

In [59]:
ni_nstd = ni[:, np.newaxis]
ni_nstd

array([[1],
       [2],
       [0]])

In [51]:
aa[aii_nstd]

<Array [[[10, 11, 12]], [[...]], [[0, 1, 2]]] type='3 * 1 * var * int64'>

In [56]:
aa[list(aii_nstd)]

<Array [[1], [12], [20]] type='3 * var * int64'>

In [57]:
na = np.array(aa.to_list())
na

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [60]:
na[ni]

array([[10, 11, 12],
       [20, 21, 22],
       [ 0,  1,  2]])

In [61]:
na[:, ni]

array([[ 1,  2,  0],
       [11, 12, 10],
       [21, 22, 20]])

In [62]:
na[[[1],[2],[0]]]

array([[[10, 11, 12]],

       [[20, 21, 22]],

       [[ 0,  1,  2]]])

In [63]:
aa[[[1],[2],[0]]]

<Array [[1], [12], [20]] type='3 * var * int64'>

In [64]:
indices = np.array([1, 2, 0])
indices

array([1, 2, 0])

In [67]:
result = na[np.arange(len(indices)), indices]
result

array([ 1, 12, 20])

In [68]:
aa[np.arange(len(aa)), ai]

<Array [1, 12, 20] type='3 * int64'>

In [69]:
in_smith = ak.Array([True, False, True])

In [70]:
np.count_nonzero(in_smith)

np.int64(2)